(()=>{
const A=window.ASA;if(!A)return;
A.recent=function(){try{return JSON.parse(localStorage.getItem('asa_recent')||'[]')}catch{return[]}};
A.addRecent=function(id){let a=A.recent().filter(x=>String(x)!==String(id));a.unshift(Number(id));localStorage.setItem('asa_recent',JSON.stringify(a.slice(0,12)))};
A.theme=function(){return localStorage.getItem('asa_theme')||'light'};
A.toggleTheme=function(){let n=A.theme()==='dark'?'light':'dark';localStorage.setItem('asa_theme',n);document.documentElement.dataset.theme=n;return n};
function inject(){
 document.documentElement.dataset.theme=A.theme();
 if(!document.getElementById('asa2026style')){let s=document.createElement('style');s.id='asa2026style';s.textContent=`[data-theme=dark] body{background:#0e1117!important;color:#f4f6f8}[data-theme=dark] .box,[data-theme=dark] .card,[data-theme=dark] .panel,[data-theme=dark] .item,[data-theme=dark] input,[data-theme=dark] select,[data-theme=dark] textarea{background:#171b22!important;color:#f4f6f8!important;border-color:#2a3039!important}[data-theme=dark] .muted{color:#aeb6c1!important}.asa-float{position:fixed;right:16px;bottom:82px;z-index:999;display:flex;flex-direction:column;gap:8px}.asa-float a,.asa-float button{width:48px;height:48px;border-radius:50%;display:grid;place-items:center;text-decoration:none;border:0;box-shadow:0 6px 22px #0003;background:#111;color:#fff;font-size:20px}.asa-float .wa{background:#087f46}.asa-top{position:fixed;right:16px;bottom:20px;z-index:998;border:0;border-radius:50%;width:42px;height:42px;display:none;background:#111;color:#fff}.asa-top.show{display:block}.asa-benefits{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin:14px 0}.asa-benefits div{background:linear-gradient(135deg,#fff,#f7f1f5);border:1px solid #eadde5;padding:14px;border-radius:14px}.asa-benefits b{display:block;margin-bottom:3px}@media(max-width:700px){.asa-benefits{grid-template-columns:repeat(2,1fr)}.asa-float{bottom:76px;right:10px}}`;document.head.appendChild(s)}
 if(!document.querySelector('.asa-float')){let d=document.createElement('div');d.className='asa-float';d.innerHTML=`<a class="wa" aria-label="WhatsApp" href="https://wa.me/8801626201990?text=${encodeURIComponent('ASA Fashion Collection BD - I need help')}">☘</a><a aria-label="Call" href="tel:+8801626201990">📞</a><a aria-label="Facebook" href="https://www.facebook.com/asafashioncollectionbd">f</a><button title="Dark mode" onclick="ASA.toggleTheme();location.reload()">☾</button>`;document.body.appendChild(d)}
 if(!document.querySelector('.asa-top')){let b=document.createElement('button');b.className='asa-top';b.textContent='↑';b.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.body.appendChild(b);addEventListener('scroll',()=>b.classList.toggle('show',scrollY>500))}
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',inject);else inject();
})();